[package]
name = "see-u-l4ter"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
hmac = "0.12.1"
sha2 = "0.10.8"
hex-literal = "0.4.1"
base64 = "0.22.0"
chrono = "0.4.37"
tokio = { version = "1.37.0", features = ["full"] }
warp = "0.3"
clap = "4.5.4"
